Vagrantfile-centric version for build agents
reside-ic/reside-hyperv-scripts pull request #2
Opened 2020-10-05 16:16 UTC by weshinsley

2020-10-06 15:02 UTC, weshinsley commented
Hi @richfitz @r-ash - github still feels my PR is only worthy of one person's attention!

So this one (prompted by Rich last week) forced me to learn a little more Vagrant, and it ends up with a neater method than PR #1 and slightly adjusted purpose too - for #1 I was thinking of a toolkit to spin up and down things at will; this one is more towards a reproducible deployment, with "vagrant up" spinning up the 5 agents. It removes the need for powershell - not that it was so bad - I actually found it fairly civilised to work with, but it's another "thing" to have. 

Compared to the buildkite-agent repo - at the moment, the Vagrantfile here is set for hyper-v, so if we wanted to spin up more agents on a linux host, buildkite-agent would still be the way. But there's nothing much platform-specific in the Vagrantfile; just the hyperv provider string.

Main differences in approach compared to buildkite-agent are...
1) packer is available for Windows/Hyper-V, but it threw a dirty error when trying to attach the ISO (which I think is to do with cloud-init, to automate getting the server up and running the first time). But I found vagrant targetting hyper-v could do all the things that I needed it to, which packer would otherwise have done.

2) The only vagrant hurdle on hyper-v is about networking (See https://www.vagrantup.com/docs/providers/hyperv/limitations) - so I had to move that as a provision script with args about each agent from the Vagrantfile. So a bit of workaround for hyper-v here - but should be work fine on a linux host too.

Windows 2019 now seems to happily pop up a bash window for running .sh scripts now, so that, combined with vagrant being cross-platform makes this seem quite flexible and easy, with almost all shared stuff between linux and windows.

2020-10-06 15:06 UTC, weshinsley commented
PS - should we make this repo public and tag it with hacktoberfest? :-P

2020-10-06 15:06 UTC, richfitz commented
> PS - should we make this repo public and tag it with hacktoberfest? :-P


haha, if you want

2020-10-06 15:12 UTC, richfitz requested changes
I'd like to see instructions for doing this so that I or someone else can restart agents while you're away. Apologies if I've missed that. Other minor comments below

2020-10-06 15:12 UTC, richfitz commented on build-kite/Vagrantfile
> +# vagrant doesn't support setting the disk size yet for hyper-v
The disk size was done with a plugin for montagu (only for persistent disks) and otherwise for virtualbox it was based on the image itself, which felt weird. 128GB is a great size though, so that's fine. Can you delete the comment with 40GB here?

2020-10-06 15:12 UTC, richfitz commented on build-kite/Vagrantfile
> +  { :hostname => 'reside-bk1', :ip => '14.0.0.2', :gw => '14.0.0.1', :ram => '16384', :mac => "00:15:5d:1a:84:20"},
Do we imagine gw and ram ever differing? If not shall we lift them up to the global scope and out of the hash here?

2020-10-06 15:12 UTC, richfitz commented on build-kite/vm_scripts/start-agent.sh
> +
Here, we might set up some metadata for the agents.

https://buildkite.com/docs/agent/v3/cli-meta-data#setting-data

In particular, something that says that the os is ubuntu and that these are "general" nodes. Over time we can then target our builds onto general nodes and when I build a gpu agent it'll be easy to target that.

2020-10-07 08:35 UTC, weshinsley commented on build-kite/Vagrantfile
> +  { :hostname => 'reside-bk1', :ip => '14.0.0.2', :gw => '14.0.0.1', :ram => '16384', :mac => "00:15:5d:1a:84:20"},
Done

2020-10-07 08:36 UTC, weshinsley commented on build-kite/vm_scripts/start-agent.sh
> +
Done - `--tags "ubuntu,general-node"` after start buildkite-agent

2020-10-07 08:40 UTC, weshinsley commented on build-kite/Vagrantfile
> +# vagrant doesn't support setting the disk size yet for hyper-v
Done

2020-10-07 08:44 UTC, weshinsley commented
Hmm, not sure if the hacktoberfest-accepted label works! Oh well...! 
Perhaps I need to not add it myself to my own PR - which would be a sort of easy way to be annoying...
Oh wait, it's still private.

2020-10-07 08:48 UTC, weshinsley commented
Documentation - at https://mrc-ide.myjetbrains.com/youtrack/articles/mrc-A-2/Buildkite - I'll also update the README.md...

2020-10-07 08:49 UTC, weshinsley commented
I also wonder if I should re-engineer the mint/data/vault VM scripts into vagrant files.

2020-10-07 09:11 UTC, weshinsley commented
Incorporated https://github.com/reside-ic/buildkite-agent/pull/10

2020-10-07 09:25 UTC, weshinsley commented
Pause for a minute - the tags bit doesn't work. "--tags" gets sent to systemctl instead of to the build kite.

2020-10-07 10:11 UTC, weshinsley commented
That's got it.

2020-10-08 07:56 UTC, richfitz approved these changes

2020-10-08 07:56 UTC, merged