Add HIV ssh key to buildkite agents
reside-ic/reside-hyperv-scripts pull request #22
Opened 2022-01-05 12:38 UTC by r-ash

2022-01-06 17:55 UTC, richfitz requested changes

2022-01-06 17:55 UTC, richfitz commented on build-kite/vm_scripts/start-agent.sh
> +# Add ssh key for authenticating with HIV servers (for running deployments via buildkite)
should these be on every agent? or just the one that is doing the hiv deployment?

2022-01-07 15:04 UTC, r-ash commented on build-kite/vm_scripts/start-agent.sh
> +# Add ssh key for authenticating with HIV servers (for running deployments via buildkite)
Thanks, no they don't need to be. Updated that so they only get put on "deploy" type agents

2022-01-07 16:07 UTC, richfitz approved these changes

2022-01-07 16:07 UTC, merged