Turn off password login by default
reside-ic/reside-hyperv-scripts pull request #28
Opened 2022-04-04 13:37 UTC by r-ash

We want to turn off password login for db-experiment VM. But we probably want to do this for all VMs by default.

The VMs which use this script are
* db-experiment
* ncov-dev
* comet
* covid19-forecasts
* mint-dev
* bots

Are there any of these we want to keep password login on?

2022-04-04 13:39 UTC, richfitz commented
> Are there any of these we want to keep password login on?

No, I don't think there's any good reason to

2022-04-04 13:43 UTC, richfitz requested changes
You should also pop our public keys into the new default user's `~/.ssh/authorized_keys`.  These are safe to be in public.

Either grab these from an existing deployment or you can pull a list with:

```
curl https://github.com/richfitz.keys
```

repeat for the other users. I'd suggest doing that in a script in this repo that is run infrequently rather than on deployment though?

2022-04-07 10:23 UTC, r-ash commented
Added a nice script for managing this, let me know what you think. Also let me know if any of the particular users on different machines needs to be changed - this was mostly a guess about who needs access to what. I will port this to hiv-hyperv-scripts if it looks right.

2022-04-07 10:26 UTC, richfitz approved these changes

2022-04-07 10:26 UTC, merged